export const SNAP_POINT_TOLERANCE_PX = 10

export const MOVEMENT_THRESHOLD_PX = 3

export const RUBBERBAND_ELASTICITY = 0.25
export const RUBBERBAND_ELASTICITY_STRONG = 0.5

export const DEFAULT_VELOCITY_THRESHOLD = 0.5
